name: Tests

on:
  push:
    branches: [ tests-workflow ]
  pull_request:
    branches: [ develop ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest ]
        branch: [ upgrade_deps]
    runs-on: ${{ matrix.os }}

    steps:

      - name: Clone workspaces
        uses: actions/checkout@v3
        with:
          repository: prosopo/workspaces
          path: workspaces
          submodules: recursive
          ref: ${{ matrix.branch }}

      - name: Clone scripts repository
        uses: actions/checkout@v3
        with:
          repository: prosopo/scripts
          path: scripts
          ref: ${{ matrix.branch }}

      - name: Start the docker images
        run: |
          cd scripts
          docker compose --file ./docker/docker-compose.development.yml up -d

      - name: Cache node modules
        id: cache-npm
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - if: ${{ steps.cache-npm.outputs.cache-hit != 'true' }}
        name: List the state of node modules
        continue-on-error: true
        run: npm list

      - name: Install dependencies
        run: |
          cd workspaces
          npm install
          npm run checkout ${{ matrix.branch }}

      - name: Build provider and dependencies
        run: |
          cd workspaces
          cat package.json
          npm run build+deps provider

      - name: Setup the environment
        run: |
          cd workspaces
          npm run setup

      - name: Run the unit tests
        run: |
          cd workspaces
          npm run test

