name: Tests

on:
  pull_request:
    branches: [ develop, main ]

env:
  CARGO_TERM_COLOR: always
  ENVIRONMENT: development
  GH_TOKEN: ${{ github.token }}

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest ]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Check github refname
        run: |
          echo ${{ github.ref }}
          echo ${{ github.ref_name }}
          echo ${{ github.head_ref }}
          echo ${{ github.base_ref }}

      - name: Remove stopped containers
        run: docker rm $(docker ps -a -q) || true

      - name: Clone workspaces
        uses: actions/checkout@v3
        with:
          repository: prosopo/workspaces
          path: workspaces
          submodules: recursive
          #ssh-key: ${{ secrets.SSH_KEY }}
          #ssh-strict: false

      - name: Checkout correct workspaces branch
        run: |
          cd workspaces
          git fetch
          git checkout ${{ github.head_ref }} || git checkout ${{ github.base_ref }} || git checkout develop
          git pull

      - name: Clone scripts repository
        uses: actions/checkout@v3
        with:
          repository: prosopo/scripts
          path: scripts
          #ssh-key: ${{ secrets.SSH_KEY }}
          #ssh-strict: false

      - name: Checkout correct scripts branch
        run: |
          cd scripts
          git fetch
          git checkout ${{ github.head_ref }} || git checkout ${{ github.base_ref }} || git checkout develop
          git pull

      - run: mkdir -p ~/image-cache

      - id: image-cache
        uses: actions/cache@v3
        with:
          path: ~/image-cache
          key: image-cache-docker-${{ runner.os }}

      - if: steps.image-cache.outputs.cache-hit != 'true'
        run: |
          docker pull prosopo/substrate:demo-v1.0.5
          docker save -o ~/image-cache/prosopo.tar prosopo/substrate:demo-v1.0.5
          docker pull mongo:5.0.4
          docker save -o ~/image-cache/mongo.tar mongo:5.0.4

      - if: steps.image-cache.outputs.cache-hit == 'true'
        run: |
          ls ~/image-cache
          docker load -i ~/image-cache/prosopo.tar
          docker load -i ~/image-cache/mongo.tar

      - name: Start the docker images
        run: |
          cd scripts
          docker compose --file ./docker/docker-compose.development.yml up -d

      - name: Checkout correct submodule branches
        run: |
          cd workspaces
          git submodule foreach 'echo $(git remote -v)'
          git submodule foreach 'git config remote.origin.fetch "+refs/heads/*:refs/remotes/origin/*"'
          git submodule foreach 'git fetch origin'
          git submodule foreach 'git checkout ${{ github.head_ref }} || git checkout ${{ github.base_ref }} || git checkout develop'
          git submodule foreach 'echo "pulling..." && git pull'

      - id: node-cache
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: node-cache-${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            node-cache-${{ runner.os }}-

      - if: ${{ steps.node-cache.outputs.cache-hit == 'true' }}
        run: |
          cd ~/.npm
          ls

      - name: Install dependencies
        run: |
          cd workspaces
          npm install

      - name: Build provider and dependencies
        run: |
          cd workspaces/packages/common && echo $(pwd) && npm run build
          cd workspaces/packages/contract && echo $(pwd) && npm run build
          cd workspaces/packages/datasets && echo $(pwd) && npm run build
          cd workspaces/packages/provider && echo $(pwd) && npm run build

      - name: Setup the environment and run the unit tests
        run: |
          cd workspaces
          git status | head -n 1
          NODE_ENV=$ENVIRONMENT npm run setup
          cd packages/provider
          git status | head -n 1
          docker container ls
          cat .env.development
          NODE_ENV=$ENVIRONMENT npm run test

      - name: Remove the docker containers
        run: |
          cd scripts
          docker compose --file ./docker/docker-compose.development.yml down

