name: Tests

on:
  push:
    branches: [ tests-workflow ]
  pull_request:
    branches: [ develop ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest ]
    runs-on: ${{ matrix.os }}

    steps:

      - name: Checkout provider
        uses: actions/checkout@v2
        with:
          repository: prosopo/workspaces
          path: workspaces
          submodules: recursive
          branch: upgrade_deps

      - name: Clone scripts repository
        uses: actions/checkout@v2
        with:
          repository: prosopo/scripts
          path: scripts
          branch: upgrade_deps

      - name: Run the unit tests
        run: |
          cd scripts
          docker compose --file ./docker/docker-compose.development.yml up -d

      - name: Install dependencies
        run: |
          cd workspaces
          npm i

      - name: Build provider and dependencies
        run: |
          cd workspaces
          npm run bd provider

      - name: Setup the environment
        run: |
          cd workspaces
          npm run setup

      - name: Run the unit tests
        run: |
          cd workspaces
          npm run test

